[plugins]
# Rocks
"rocks.nvim" = "scm"
"rocks-git.nvim" = "scm"
"rocks-treesitter.nvim" = "scm"

# Mini
"mini.nvim" = "scm"
"mini.starter" = "scm"
"mini.notify" = "scm"
"mini.comment" = "scm"
"mini.surround" = "scm"
"mini.pairs" = "scm"
"mini.sessions" = "scm"
"mini.icons" = "scm"
"mini.diff" = "scm"
"mini.statusline" = "scm"
"mini.tabline" = "scm"
"mini.indentscope" = "scm"
"mini.completion" = "scm"
"mini.pick" = "scm"

# LSP
nvim-lspconfig = "scm"
"mason.nvim" = "scm"
"mason-lspconfig.nvim" = "scm"

# Code snippets
luasnip = "scm"
friendly-snippets = "scm"

# Terminal
"toggleterm.nvim" = "scm"

# Treesitter syntax
tree-sitter-lua = "scm"
tree-sitter-toml = "scm"
tree-sitter-gitcommit = "scm"
tree-sitter-git_rebase = "scm"

# Dracula themes
[plugins."dracula.nvim"]
git = "Mofiqul/dracula.nvim"

[plugins."mini.git"]
git = "echasnovski/mini-git"

[treesitter]
auto_highlight = "all"
auto_install = "no"
