# System special
if [ $(uname -s) = Darwin ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    [ -d "/Applications/OrbStack.app" ] && source $HOME/.orbstack/shell/init.zsh 2>/dev/null || :
fi

# Direnv
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook zsh)"

# Python
if [ $(uname -s) = Darwin ]; then
    command -v python3 >/dev/null 2>&1 && source $HOMEBREW_PREFIX/bin/virtualenvwrapper.sh
fi