# System special
if [ $(uname -s) = Darwin ]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
fi

# Direnv
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook zsh)"

# Python
if [ $(uname -s) = Darwin ]; then
    command -v python3 >/dev/null 2>&1 && source $HOMEBREW_PREFIX/bin/virtualenvwrapper.sh
fi

