# Color
export CLICOLOR=1

# XDG
export XDG_CONFIG_HOME=${XDG_CONFIG_HOME:-$HOME/.config}
export XDG_DATA_HOME=${XDG_DATA_HOME:-$HOME/.local/share}
export XDG_STATE_HOME=${XDG_STATE_HOME:-$HOME/.local/state}
export XDG_CACHE_HOME=${XDG_CACHE_HOME:-$HOME/.cache}

# PATH
export LOCAL_PREFIX=${LOCAL_PREFIX:-$HOME/.local}
export PATH=$PATH:$LOCAL_PREFIX/bin

# Editor
export VISUAL="emacsclient -t"
export EDITOR=$VISUAL

# Zsh
export ZSH=$XDG_CONFIG_HOME/zsh

# History
export HISTFILE=$HOME/.zsh_history
export HISTSIZE=1000
export SAVEHIST=1000

# macOS
if [ $(uname) = Darwin ]; then
    export LSCOLORS=exfxcxdxbxegedabagacad
    # Homebrew
    export HOMEBREW_NO_ENV_HINTS=1
    export HOMEBREW_API_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles/api"
    export HOMEBREW_BOTTLE_DOMAIN="https://mirrors.tuna.tsinghua.edu.cn/homebrew-bottles"
    export HOMEBREW_BREW_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git"
    export HOMEBREW_CORE_GIT_REMOTE="https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git"
    export HOMEBREW_PIP_INDEX_URL="https://pypi.tuna.tsinghua.edu.cn/simple"
fi

# Python
if command -v python3 >/dev/null 2>&1; then
    export WORKON_HOME=$HOME/.virtualenvs
    export VIRTUALENVWRAPPER_PYTHON=$(command -v python3)
fi

# GnuPG
if command -v gpg >/dev/null 2>&1; then
    export GPG_TTY=$(tty)
fi